In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from collections import Counter

%matplotlib inline
sns.set(style="whitegrid")
warnings.filterwarnings("ignore")

In [2]:
# get titanic & test csv files as a DataFrame
training = pd.read_csv("train.csv")

In [3]:
training.head() # print first 5 rows

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
training.describe() # some interesting statistics for features

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
training.keys() # Show features names

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [7]:
training = training.drop(['Name','Ticket', 'Cabin'], axis=1)

In [8]:
training.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [9]:
# Filling missing age values with median
training.Age = training.Age.fillna(training.Age.median())

In [10]:
# Age is now completed
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


In [11]:
Counter(training.Embarked.values)

Counter({'S': 644, 'C': 168, 'Q': 77, nan: 2})

In [12]:
training.Embarked = training.Embarked.fillna('S')

In [13]:
# Embarked is now completed
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


In [51]:
training.to_csv("cleaned_car_data.csv")

In [14]:
Counter(training.Pclass.values)

Counter({3: 491, 1: 216, 2: 184})

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_all = training.drop('Survived', axis=1)
y_all = training.Survived

In [17]:
X_all.to_csv('test.csv')
X_all.set_index('PassengerId', inplace=True)

In [18]:
num_test = 0.20
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=num_test, random_state=23)

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [20]:
ohe=OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe.fit(X_all[['Sex','Embarked']])

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [21]:
ohe.categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [22]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Sex','Embarked']),
                                    remainder='passthrough')

In [23]:
column_trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['female', 'male'], dtype=object),
                                                           array(['C', 'Q', 'S'], dtype=object)]),
                                 ['Sex', 'Embarked'])])

In [24]:
X_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 55.7+ KB


In [25]:
from sklearn.metrics import accuracy_score
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
# from xgboost import XGBClassifier

In [26]:
rf_clf = RandomForestClassifier()


In [27]:
pipe=make_pipeline(column_trans,rf_clf)

In [28]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['female', 'male'], dtype=object),
                                                                            array(['C', 'Q', 'S'], dtype=object)]),
                                                  ['Sex', 'Embarked'])])),
                ('randomforestclassifier', RandomForestClassifier())])

In [29]:
pred_rf=pipe.predict(X_test)

In [30]:
accuracy_score(y_test, pred_rf)

0.7932960893854749

In [31]:
# xg_clf = XGBClassifier()
# pipe=make_pipeline(column_trans,xg_clf)
# pipe.fit(X_train,y_train)
# pred_xgb=pipe.predict(X_test)
# accuracy_score(y_test, pred_xgb)

0.7988826815642458

In [32]:
X_test.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [33]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array([1,'female',17.0,0,1,53.1000,'S']).reshape(1,7)))

array([1])

In [34]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array([3,'male',23,0,0,0,'S']).reshape(1,7)))

array([0])

In [35]:
import joblib
import pickle

In [36]:
# pickle.dump(xg_clf, open('model/xgb_clf.pkl', 'wb'))
pickle.dump(rf_clf, open('model/rf_clf.pkl', 'wb'))

In [71]:
# pickle.dump(pipe,open('model/xgb_clf.pkl','wb'))
pickle.dump(pipe,open('model/rf_clf.pkl','wb'))
joblib.dump(pipe,open('model/rf_clf.joblib','wb'))

In [38]:
# xgb = pickle.load(open( "model/xgb_clf.pkl", "rb" ))

In [63]:
rfc = pickle.load(open( "model/rf_clf.pkl", "rb" ))

In [40]:
Rose_DeWiit_Bukater=[1,'female',17.0,0,1,53.1000,'S']
Jack_Dawson=[3,'male',23,0,0,0,'S']

In [103]:
a=pd.DataFrame(dict(zip(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'],Rose_DeWiit_Bukater)), index=[0])
a

Pclass     Sex   Age  SibSp  Parch  Fare Embarked
0       1  female  17.0      0      1  53.1        S

In [81]:
# l=[Rose_DeWiit_Bukater]
# xgb.predict(pd.DataFrame(a))

array([1])

In [64]:
rfc.predict(pd.DataFrame(columns=['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 
                         data=np.array(l).reshape(len(l),7)))

array([1])

In [100]:
a=pd.DataFrame(columns=['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], 
                         data=np.array(l))

In [98]:
rfc.predict(a)[0]

1